### ISSUE TITLE
Email Template can't override now.

### ISSUE THREAD

**Issue by makolivares** [dnadesign/silverstripe-elemental-userforms#40]
```yaml
SilverStripe\UserForms\Model\UserDefinedForm: 
  email_template_directory: mysite/templates/useremails/
```

I have this on my config.yml to override the email templates but unfortunately it is not working anymore.

And email templates are in themes/mysite/templates/useremails/

**Comment by robbieaverill** [comment]
Hi @makolivares, this issue is best suited to be logged on github.com/silverstripe/silverstripe-userforms.

In your example, your `mysite` is a theme. I've tested your example using the following configuration and it is working correctly for me:

```yaml
SilverStripe\UserForms\Model\UserDefinedForm:
  email_template_directory: themes/mysite/templates/useremails/
```

Note that I've changed "useremails" to "userforms" in my test, but that won't matter provided your config matches your folder structure.

![image](https://user-images.githubusercontent.com/5170590/56491641-54b3f100-653d-11e9-822c-af270fb522d8.png)

![image](https://user-images.githubusercontent.com/5170590/56491646-5a113b80-653d-11e9-92d0-d65963c5698b.png)

I've also tested this by putting the templates in `app/templates/useremails` (as a project level template, rather than a theme) which is also working for me with the following config:

```yaml
SilverStripe\UserForms\Model\UserDefinedForm:
  email_template_directory: app/templates/useremails
```

I'm going to close this issue, but feel free to reopen another on the userforms repository if you are able to reproduce a bug in the module. Thanks for taking the time to raise this issue =)

**Comment by kinglozzer** [comment]
For anyone else that stumbles upon this: you’ll also need to set this config on the _element_ userform model. E.g:

```yml
DNADesign\ElementalUserForms\Model\ElementForm:
  email_template_directory: app/templates/useremails
SilverStripe\UserForms\Model\UserDefinedForm:
  email_template_directory: app/templates/useremails
```
