### ISSUE TITLE
Graphlq 4 support

### ISSUE THREAD

**Issue by palomamtnez** [dnadesign/silverstripe-elemental-userforms#76]
Im a bit new to Silverstripe, so I was just wondering if there are any examples of how to use this library on my Silverstripe 5 headless site via Graphql.

At the moment, my `_graphql/models.yml` file looks like this:
```
Page:
  fields:
    "*": true
  operations:
    read: true
App\HomePage:
  fields:
    "*": true
  operations:
    read: true

SilverStripe\CMS\Model\SiteTree:
  fields:
    "*": true
    bannerLinkImageURL:
      type: String
      property: resolveBannerLinkImageURL
    bannerLink:
        type: String
        property: resolveBannerLink
    children:
      type: "[SiteTreeInterface]"
      property: Children
  operations:
    read: true

DNADesign\Elemental\Models\ElementalArea:
  fields:
    "*": true
  operations:
    readOne: true
DNADesign\Elemental\Models\BaseElement:
  fields: '*'
  operations:
    read: true
DNADesign\Elemental\Models\ElementContent:
  fields: '*'
  operations:
    read: true
```

And my query looks like this:

```
query pages {
  readHomePages(filter: { id: { eq: "1" } }, limit: 1) {
    nodes {
      id
      title
      elementalArea {
        elements {
          nodes {
            ... on ElementContent {
              id
              html
              title
            }
            ... on BaseElement {
              __typename
              title
            }
          }
        }
      }
    }
  }
}

```

and the results look like this:

```
{
  "data": {
    "readHomePages": {
      "nodes": [
        {
          "id": "1",
          "title": "Homeaa 1",
          "elementalArea": {
            "elements": {
              "nodes": [
                {
                  "__typename": "BaseElement",
                  "title": "test form" <--- This is the form I have created via the admin panel, need to access to the fields, settings, etc.
                },
                {
                  "__typename": "ElementContent",
                  "id": "1",
                  "html": "<p>testing!&nbsp;</p>",
                  "title": "test111"
                }
              ]
            }
          }
        }
      ]
    }
  }
}
```

Thanks
